### ISSUE TITLE
(require 'charmap) doesn't work; (load-file "[etc]/charmap.el") required

### ISSUE THREAD

**Issue by flexibeast** [lateau/charmap#6]
I've just installed charmap via the Emacs package manager - charmap version is reported as '20131019.2158'.

Doing a (require 'charmap) doesn't result in any symbols from charmap.el being loaded; so e.g. the 'charmap' interactive command isn't available, the const charmap-char-map isn't defined, and internal functions like 'charmap-print' aren't defined.

However, when I load-file the 'charmap.el' file, everything becomes available.

I'm running a manually-compiled Emacs 24.3 on Debian Wheezy.

**Comment by lateau** [comment]
@flexibeast 

Ok, I'll fix it on next release. Thanks.

**Comment by piyo** [comment]
Hello I fixed this problem in that PR #7, please review it.
