### ISSUE TITLE
Invalid face reference on zoom

### ISSUE THREAD

**Issue by lateau** [lateau/charmap#9]
@piyo I found this message when I tried your new feature charmap-zoom-char-at-point.
Can you resolve this?

```
Invalid face reference: quote
Invalid face attribute :inherit (quote charmap-onechar-face)
Invalid face reference: quote
Invalid face attribute :inherit (quote charmap-onechar-face)
```

**Comment by piyo** [comment]
Woops, I haven't tried vanilla Emacs yet. I will be testing on Windows first, and then Linux (Debian Jessie) next.
